# Site settings
name: longkyzhang
location: Canton.China
company: Tech inc.
position: Software Dev
github: https://github.com/zlonqi
facebook: 
phone: 匿
email: zlonqi@163.com

baseurl: ""

permalink: /:year/:month/:day/:title/

#exclude: ['README.md']

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
