# Site settings
name: longkyzhang
location: canton.China
company: T inc.
position: software dev
github: https://github.com/zlonqi
facebook: https://www.google.com/maps/d/u/0/edit?mid=1R8eJXu8H6M43Rpaxay08s1va8PXpZuql&usp=sharing
phone: 匿
email: zlonqi@163.com

baseurl: ""

permalink: /:year/:month/:day/:title/

#exclude: ['README.md']

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
