# Site settings
name: 张珑脐
location: 中国广州
company: 华南理工 | 软件工程
position: 服务端、高性能、信息安全
github: https://github.com/zlonqi/longky
facebook: https://www.facebook.com/zlonqi
phone: 13879502493
email: zlonqi@163.com

baseurl: "/zlonqi"

permalink: /:year/:month/:day/:title/

#exclude: ['README.md']

# Build settings
markdown: kramdown
