# Site settings
name: 张珑脐
location: China
company: longqi
position: R&D
github: https://github.com/zlonqi
twitter: https://www.yuque.com/longky
phone: stand2win
email: zlonqi@163.com

baseurl: ""

permalink: /:year/:month/:day/:title/

#exclude: ['README.md']

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
