# Site settings
name: 张珑脐
location: 中国大陆
company: longkyzhang 
position: 服务端开发者
github: https://github.com/zlonqi/longky
facebook: https://www.google.com/maps/d/u/0/edit?mid=1R8eJXu8H6M43Rpaxay08s1va8PXpZuql&usp=sharing
phone: 13879502493
email: zlonqi@163.com

baseurl: "/zlonqi.github.io"

permalink: /:year/:month/:day/:title/

#exclude: ['README.md']

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
